<a href="https://colab.research.google.com/github/BautistaBertolami/Cap4630AI/blob/master/HW4/HW4Problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Homework 4 Problem 2 maxpooling2d using numpy

In [0]:
import numpy as np

def applyWindow(input_mat, x, y, s, irows, icols):
  max = 0

  for r in range(0, s):
    for c in range(0, s):
      if(r + x < irows and c + y < icols):
        num = input_mat[r + x][c + y]
        if(max < num):
          max = num 

  return max

def maxpooling2d(input_mat, s):
  irows = np.size(input_mat, 0)
  icols = np.size(input_mat, 1)

  if(s > irows or s > icols):
    return []

  resultMatrix = np.empty([int(np.ceil(irows/s)), int(np.ceil(icols/s))])

  for r in range(0, irows, s):
    for c in range(0, icols, s):
      res = applyWindow(input_mat, r, c, s, irows, icols)
      resultMatrix[int(r/2)][int(c/2)] = res

  return resultMatrix

Test Cases

In [0]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                          [2, 4, 2, 1, 0, 3],
                          [1, 2, 4, 2, 4, 5],
                          [2, 1, 2, 1, 2, 1],
                          [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  #output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")


[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!
