<a href="https://colab.research.google.com/github/BautistaBertolami/Cap4630AI/blob/master/HW4/HW4Problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Homework 4 problem 1 conv2d using only numpy\
applyKernel is a helper function that obtains the convolution in one area of the original input matrix\
conv2d just gets the convolution of the input matrix using the kernel matrix


In [0]:
import numpy as np

def applyKernel(input_mat, kernel_mat, x, y, krows, kcols):
  total = 0

  for r in range(0, krows):
    for c in range(0, kcols):
      total += kernel_mat[r][c]*input_mat[r + x][c + y] 

  return total

def conv2d(input_mat, kernel_mat):
  kernel_mat = np.flip(kernel_mat)
  irows = np.size(input_mat, 0)
  icols = np.size(input_mat, 1)
  krows = np.size(kernel_mat, 0)
  kcols = np.size(kernel_mat, 1)
  rrows = irows - krows + 1
  rcols = icols - kcols + 1

  if(krows != kcols):
      # kernel matrix is not a square
      return []

  if(irows != icols):
      # input matrix is not a square
      return []

  if(krows > irows or kcols > icols):
    return []

  resultMatrix = np.empty([rrows, rcols])

  for r in range(0, rrows):
    for c in range(0, rcols):
      res = applyKernel(input_mat, kernel_mat, r, c, krows, kcols)
      resultMatrix[r][c] = res

  return resultMatrix


Test Cases

In [8]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  #if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
  #  output_mat = []
  #else:
  #  output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")


[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!

[]
Correct output!

