<a href="https://colab.research.google.com/github/BautistaBertolami/Cap4630AI/blob/master/HW1BautistaBertolami.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bautista Bertolami

The multiply_matrices function's purpose is to multiply a list of matrices in total to create one single matrix.

The function has two helper functions \
isEmpty - it just returns if a list is empty or not \
\
matrixMult - this function returns the result of multiplying 2 matrices together \
It does not return a result if the matrices are not compatible this meaning that the matrices do not match in number of rows and columns. Example here \
\begin{bmatrix}
a & b & c\\
d & e & f
\end{bmatrix}
\begin{bmatrix}
g & h & i\\
j & k & l
\end{bmatrix} \
These can't be multiplied as the number of rows in the first matrix does not match the number of columns in the second, and vice versa



In [26]:
import numpy as np

def matrixMult(testMatrix1, testMatrix2):
  
  #print(testMatrix1)
  #print(testMatrix2)

  shape1 = testMatrix1.shape
  shape2 = testMatrix2.shape

  if shape1[1] == shape2[0]:

    #print("Multiplying Matrix1 X Matrix2")
    resultMatrix = np.empty([shape1[0],shape2[1]])
    np.matmul(testMatrix1, testMatrix2, resultMatrix)

    return resultMatrix

  elif shape1[0] == shape2[1]:

    #print("Multiplying Matrix2 X Matrix1")
    resultMatrix = np.empty([shape1[1],shape2[0]])
    np.matmul(testMatrix2, testMatrix1, resultMatrix)

    return resultMatrix

  else:

    print("The matrices\n{0} and\n{1}\ncan't be multiplied because the columns and rows do not match\n{2} != {3}".format(testMatrix1, testMatrix2, shape1, shape2))
    return

def isEmpty(matrixList):
  if matrixList:
    return False
  else:
    return True


def multiply_matrices(matrixList):

  if(isEmpty(matrixList)):
    print("The list of matrices is empty")
    return

  testMatrix = matrixList[0]
  for x in range(1, len(matrixList)):
    testMatrix = matrixMult(testMatrix, matrixList[x])

  return testMatrix

#main loop
matrix1 = np.array(([[2, 4, 6], [6, 2, 4], [4, 6, 2]]))
matrix2 = np.random.randint(1, 9, (3, 2))
matrix3 = np.random.randint(1, 9, (2, 4))
matrix4 = np.random.randint(1, 9, (3, 4))

matrixList1 = (matrix1, matrix2, matrix3)
matrixList2 = ()
matrixList3 = (matrix1, matrix2, matrix4)

#Function Works
print(multiply_matrices(matrixList1))
print()
#Function return empty
print(multiply_matrices(matrixList2))
print()
#Function will not work
print(multiply_matrices(matrixList3))


[[452. 242. 166. 284.]
 [372. 212. 132. 244.]
 [628. 338. 230. 396.]]

The list of matrices is empty
None

The matrices
[[42. 40.]
 [32. 36.]
 [58. 56.]] and
[[3 2 7 1]
 [6 2 1 6]
 [2 3 2 6]]
can't be multiplied because the columns and rows do not match
(3, 2) != (3, 4)
None
